export const TOGGLE_PRINT_SEARCH_FORM = 'TOGGLE_PRINT_SEARCH_FORM';
export const CHANGE_INPUTS_VALUES = 'CHANGE_INPUTS_VALUES';
export const CHANGE_SEARCHED_VALUE = 'CHANGE_SEARCHED_VALUE';
export const ADD_JOBS = 'ADD_JOBS';
export const CLEAR_JOBS = 'CLEAR_JOBS';
export const TOGGLE_BACKDROP = 'TOGGLE_BACKDROP';
